[theme]
theme = "native"

[theme.overrides]
separator = " "
[icons]
icons = "awesome6"

[[block]]
block = "notify"
driver = "swaync"
format = "$icon {($notification_count.eng(w:1)) |}"
[[block.click]]
button = "left"
action = "show"

[[block]]
block = "keyboard_layout"
format = "$layout"
driver = "sway"
[block.mappings]
"English (UK)" = "en"
"Spanish (N/A)" = "es"

[[block]]
block = "sound"
driver = "pulseaudio"
format = "$output_name{$volume|}"
step_width = 1
[block.mappings]
"alsa_output.usb-C-Media_Electronics_Inc._JPL-500S-USB-00.analog-stereo" = ""
"alsa_output.pci-0000_00_1f.3.analog-stereo" = ""
"auto_null" = "None"

[[block]]
block = "net"
format = "$icon"

[[block]]
block = "battery"
format = "$icon"

[[block]]
block = "backlight"
format = "$icon" 
device = "intel_backlight"
step_width = 1

[[block]]
block = "time"
format = "$timestamp"
interval = 5
